name: Pull Request

# Run on PRs.
on: [pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - name: Prettier
        run: npx prettier --check .
      - name: Lint
        run: npx eslint .
      # Test the code in the current branch.
      - uses: ./
        with:
          upload-dir: .
          github-token: ${{ secrets.GITHUB_TOKEN }}
